### ISSUE TITLE
Can this library be used to access iCloud Drive files?

### ISSUE THREAD

**Issue by hoopes** [lionheart/requests-cloudkit#4]
Hi,

Can this library be used to access icloud drive files? If so, what would I need to do? It's difficult to understand the difference between cloudkit and icloud drive (if there is any...)

Thanks

**Comment by dlo** [comment]
Hi @hoopes. Unfortunately I don't think this is possible. I think the two systems are sandboxed to some degree, and apps only have access to within their own containers (I could be wrong, it's been a while since I looked). Let me know if there's anything else I can help out with. -Dan
