### ISSUE TITLE
TypeError on simple request

### ISSUE THREAD

**Issue by maty-bohacek** [lionheart/requests-cloudkit#8]
After the most basic setup, as included in the [README.md](README.md):

```pycon
>>> import requests
>>> from requests_cloudkit import CloudKitAuth
>>> auth = CloudKitAuth(key_id=YOUR_KEY_ID, key_file_name=YOUR_PRIVATE_KEY_PATH)
>>> requests.get("https://api.apple-cloudkit.com/database/[version]/[container]/[environment]/public/zones/list", auth=auth)
```

I am getting the following error:

**File "/opt/anaconda3/[...]/lib/python3.7/site-packages/requests_cloudkit/cloudkit.py", line 45, in make_signature
    signature = "{}:{}:{}".format(formatted_date, self.encode_body(body), path)
  File "/opt/anaconda3/[...]/lib/python3.7/site-packages/requests_cloudkit/cloudkit.py", line 62, in encode_body
    h = hashlib.sha256(body)
TypeError: Unicode-objects must be encoded before hashing**

I have tried encoding the `body` variable within the `encode_body()` method, but that did not change anything. I have also tried multiple key files and multiple containers, still no change (All of these work normally with **CloudKitJS** or my custom Java wrapper).

**Comment by 6peterlu** [comment]
I'm getting the same issue! Have you made any progress here?

**Comment by 6peterlu** [comment]
Actually, encoding the body variable in the encode_body method helped me (just pulled latest master of this repo) past that error. Still getting 401 unauthorized though, so not sure if it's reading the private key correctly

**Comment by maty-bohacek** [comment]
Hey, I was playing with the whole code for multiple days and eventually found a way around. Will try to find the solution during the weekend and send it here.

**Comment by app4g** [comment]
@matyasbohacek did you get past this? I'm still trying to get a CSV dump of CloudKit data. TX

**Comment by maty-bohacek** [comment]
@app4g I got past this, but the workaround endpoint eventually got shut down by Apple, which led me to choose a different DB. Sorry for the bad news!
